<?php 
    $customer = $block->getLoadProduct();
    $giftDateConfig = $block->getGiftDateOfCUstomer();
?>
<?php if($block->checkLogged()):?>
    <div id="popup">
    </div>
<?php endif; ?>
<style>
    .custom-modal .modal-inner-wrap{
        height: 35%;
        left: 0;
        top: 15%;
        width: 34%;
    }
</style>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($,modal) {
        let options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'Welcome Dar Customers',
            modalClass: 'custom-modal',
            buttons: [{
                text: $.mage.__('Confirm'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };
        
        let $myModal = $('#popup');
        let popup = modal(options, $myModal);
        
        //this opens the modal, you can use some click event or whatever you need to trigger the modal here
        $myModal.modal('openModal');
        // $(document).ready(function(){

        // })
    });
</script>